### ISSUE TITLE
TypeError when loading boards

### ISSUE THREAD

**Issue by setpill** [lovasoa/whitebophir#173]
### Reproduce

On a freshly installed whitebophir server, using the following steps:

```
git clone https://github.com/lovasoa/whitebophir.git
cd whitebophir
git checkout v1.9.0
npm ci --production
PORT=5001 npm start
```

### Observed behaviour

When opening the server the greeting page loads fine, but when clicking on either of the board buttons the browser just shows the error `TypeError: Cannot read property 'includes' of null`.

In the server logs I can see:

```
Trace: TypeError: Cannot read property 'includes' of null
    at BoardTemplate.parameters (/opt/whitebophir/server/templating.js:71:43)
    at BoardTemplate.serve (/opt/whitebophir/server/templating.js:49:29)
    at handleRequest (/opt/whitebophir/server/server.js:120:23)
    at Server.handler (/opt/whitebophir/server/server.js:75:5)
    at Server.<anonymous> (/opt/whitebophir/node_modules/engine.io/lib/server.js:411:24)
    at Server.<anonymous> (/opt/whitebophir/node_modules/socket.io/dist/index.js:211:28)
    at Server.emit (events.js:314:20)
    at parserOnIncoming (_http_server.js:779:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at Server.handler (/opt/whitebophir/server/server.js:77:13)
    at Server.<anonymous> (/opt/whitebophir/node_modules/engine.io/lib/server.js:411:24)
    at Server.<anonymous> (/opt/whitebophir/node_modules/socket.io/dist/index.js:211:28)
    at Server.emit (events.js:314:20)
    at parserOnIncoming (_http_server.js:779:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
```

### System info
OS: Ubuntu 18.04.5 LTS
Node version: v12.21.0
NPM version: 6.14.11

**Comment by lovasoa** [comment]
Hello and thanks for getting in touch !
  This bug was introduced by https://github.com/lovasoa/whitebophir/pull/170 and fixed in v1.9.1 which I just released.
