### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/whitebophir#72]
I think an error slipped through my review in #57 , which introduced repeated errors in production.

I think this is due to [mutating request.url](https://github.com/lovasoa/whitebophir/blob/master/server/server.js#L94), which is supposed to be read-only.

```
Trace: TypeError: Cannot read property 'length' of null
    at SendStream.hasTrailingSlash (/opt/app/node_modules/send/index.js:304:30)
    at SendStream.pipe (/opt/app/node_modules/send/index.js:590:34)
    at serveStatic (/opt/app/node_modules/serve-static/index.js:125:12)
    at handleRequest (/opt/app/server/server.js:89:5)
    at Server.handler (/opt/app/server/server.js:60:3)
    at Server.<anonymous> (/opt/app/node_modules/engine.io/lib/server.js:473:22)
    at Server.<anonymous> (/opt/app/node_modules/socket.io/lib/index.js:343:16)
    at Server.emit (events.js:310:20)
    at parserOnIncoming (_http_server.js:784:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Server.handler (/opt/app/server/server.js:62:11)
    at Server.<anonymous> (/opt/app/node_modules/engine.io/lib/server.js:473:22)
    at Server.<anonymous> (/opt/app/node_modules/socket.io/lib/index.js:343:16)
    at Server.emit (events.js:310:20)
    at parserOnIncoming (_http_server.js:784:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
```

**Comment by lovasoa** [comment]
This can be reproduced by simply loading https://wbo.ophir.dev/boards (without a trailing slash).

**Comment by lovasoa** [comment]
I think we should just disable this strange feature that we can load all resources both from `/boards/path-to-resource` AND from `/path-to-resource`. Each resource should have a unique URL.
