### ISSUE TITLE
Start up errors

### ISSUE THREAD

**Issue by fallenartist** [lovasoa/whitebophir#77]
Hi,
I'm trying to install a whiteboard on my server. I'm getting the following error:

```
[warsztatmiejski@s42]:<~/domains/makerspace.silesia.pl/public_nodejs/whitebophir>$ PORT=5001 npm start

> whitebophir@1.5.0 start /usr/home/warsztatmiejski/domains/makerspace.silesia.pl/public_nodejs/whitebophir
> node ./server/server.js

/usr/home/warsztatmiejski/domains/makerspace.silesia.pl/public_nodejs/whitebophir/server/sockets.js:42
	async function joinBoard(name) {
	      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/home/warsztatmiejski/domains/makerspace.silesia.pl/public_nodejs/whitebophir/server/server.js:2:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whitebophir@1.5.0 start: `node ./server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the whitebophir@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/warsztatmiejski/.npm/_logs/2020-05-20T11_13_59_795Z-debug.log
```

I'm not really familiar with node.js (sorry) – is this an easy fix? 
Thanks.

**Comment by lovasoa** [comment]
Hello ! It looks like you are using a very old version of node.js. whitebophir requires at least node v8.0. 

You have two possibilities : 
 - use the provided docker container instead (see the [README](https://github.com/lovasoa/whitebophir#running-your-own-instance-of-wbo) for more information)
 - update node.js (how to do so depends on your operating system)

**Comment by fallenartist** [comment]
True! Changed to v12. But now I see this:

```
[warsztatmiejski@s42]:<~/domains/makerspace.silesia.pl/public_nodejs/whitebophir>$ PORT=5001 npm start

> whitebophir@1.5.0 start /usr/home/warsztatmiejski/domains/makerspace.silesia.pl/public_nodejs/whitebophir
> node ./server/server.js

2020-05-20T15:44:35.248Z	server started	{"port":5001}
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: listen EPERM: operation not permitted 0.0.0.0:5001
    at Server.setupListenHandle [as _listen2] (net.js:1211:19)
    at listenInCluster (net.js:1276:12)
    at Server.listen (net.js:1364:7)
    at Object.<anonymous> (/usr/home/warsztatmiejski/domains/makerspace.silesia.pl/public_nodejs/whitebophir/server/server.js:25:5)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1255:8)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 'EPERM',
  errno: 'EPERM',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 5001
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whitebophir@1.5.0 start: `node ./server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the whitebophir@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/warsztatmiejski/.npm/_logs/2020-05-20T15_44_35_266Z-debug.log
```

What do you think?

BTW, my hosting provider's [wiki](https://translate.google.com/translate?sl=pl&tl=en&u=https%3A%2F%2Fwiki.mydevil.net%2FNode.js) has some info about handling node.js apps - maybe it will shed some light? Many thanks.

**Comment by lovasoa** [comment]
It lLooks like you are trying to listen to a port you don't have the right to listen to.

**Comment by fallenartist** [comment]
Thanks, I've enable the port and it's running. But... how do I access it? Sorry for the noob questions!

**Comment by lovasoa** [comment]
> how do I access it?

You should ask your hosting provider, not me 😄

**Comment by fallenartist** [comment]
I shall ask them! 😅
